package patient_data

const ROLE_ADMIN = "ADMIN"
const ROLE_PATIENT = "PATIENT"
const ROLE_HCP = "HCP"

const AUTHORIZE_NOTHING = 0
const AUTHORIZE_READABLE = 1
const AUTHORIZE_APPENDABLE = 2

const MEDICALDATATYPE_LAB = "LAB"
const MEDICALDATATYPE_DRUG = "DRUG"
const MEDICALDATATYPE_FINANCIAL = "FINANCIAL"

const ACTION_REQUEST_PERMISSION = 0
const ACTION_GRANT_PERMISSION = 1
const ACTION_READ_DATA = 2
const ACTION_APPEND_DATA = 4


